name: Xcode Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build macOS
        run: xcodebuild -scheme FHExtensions -destination 'platform=macOS'
      - name: Run macOS tests
        run: xcodebuild -scheme FHExtensions -destination 'platform=macOS' test
  
  build-macos-catalyst:
    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v2
      - name: Build macOS Catalyst
        run: xcodebuild -scheme FHExtensions -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst'
      - name: Run macOS Catalyst tests
        run: xcodebuild -scheme FHExtensions -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' test
  
  build-ios:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        run: xcodebuild -scheme FHExtensions -destination 'name=iPhone 12'
      - name: Run iOS tests
        run: xcodebuild -scheme FHExtensions -destination 'name=iPhone 12' test
  
  build-tvos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build tvOS
        run: xcodebuild -scheme FHExtensions -destination 'name=Apple TV'
      - name: Run tvOS tests
        run: xcodebuild -scheme FHExtensions -destination 'name=Apple TV' test
